#!/bin/bash

echo "Creating remote diff"

repo=`git remote -v | grep -m 1 "(push)" | sed -e "s/.*github.com[:/]\(.*\)\.git.*/\1/"`;
branch=`git name-rev --name-only HEAD`;

tobranch="master";

if [ ! -z "$1" ]; then
	tobranch=$1
fi

echo "creating diff for $tobranch...$branch";

open https://github.com/$repo/compare/$tobranch...$branch
